"""HWPX Parser V2 — error/warning codes."""
from __future__ import annotations


class WarnCode:
    ZIP_OPEN_FAIL = "ZIP_OPEN_FAIL"
    PACKAGE_STRUCTURE_WARN = "PACKAGE_STRUCTURE_WARN"
    SECTION_PARSE_WARN = "SECTION_PARSE_WARN"
    TABLE_PARSE_WARN = "TABLE_PARSE_WARN"
    MERGED_CELL_GRID_MISMATCH = "MERGED_CELL_GRID_MISMATCH"
    NESTED_TABLE_DETECTED = "NESTED_TABLE_DETECTED"
    DANGLING_STYLE_REF = "DANGLING_STYLE_REF"
    UNKNOWN_LAYOUT = "UNKNOWN_LAYOUT"
    LOW_CONFIDENCE_SLOT = "LOW_CONFIDENCE_SLOT"
    UNSUPPORTED_DRAWING = "UNSUPPORTED_DRAWING"
    IMAGE_ONLY_BLOCK = "IMAGE_ONLY_BLOCK"


class ErrCode:
    ZIP_OPEN_FAIL = "ZIP_OPEN_FAIL"
    XML_DECODE_FAIL = "XML_DECODE_FAIL"
    MISSING_REQUIRED_ENTRY = "MISSING_REQUIRED_ENTRY"
    SECTION_READ_FAIL = "SECTION_READ_FAIL"
